#draw hearth  somehow
#inport libres
import turtle
#draw heart and rose 
def draw_rose():
    turtle.color("red")
    turtle.begin_fill()
    turtle.left(140)
    turtle.forward(112)
    turtle.circle(-56, 200)
    turtle.goto(0, 0)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(56, 60)
    turtle.goto(0, 0)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.color("red")
    turtle.begin_fill()
    turtle.circle(56, 60)
    turtle.goto(0, 0)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(56, 60)
    turtle.goto(0, 0)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.color("red")
    turtle.begin_fill()
    turtle.circle(56, 60)
    turtle.goto(0, 0)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(56, 60)
    turtle.goto(0, 0)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.color("red")
    turtle.begin_fill()
    turtle.circle(56, 60)
    turtle.goto(0, 0)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0, 0)


draw_rose()